### ISSUE TITLE
Use locales

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard-2-ui-example#18]
Hi guys,

There is a json file in this repo, but I don't think it is being used.
I would like to move my hardcoded texts from my config screen to my json file, but not sure what is the best way to do that.
Would appreciate if somebody could change this example ui node to demonstrate it.
Thanks!
Bart

**Comment by joepavitt** [comment]
You can see an example of it here: https://github.com/FlowFuse/node-red-dashboard-2-ui-example/blob/a5f443e290a4d453dac46e6ad9b9845dcc5958d9/nodes/ui-example.html#L49

**Comment by bartbutenaers** [comment]
@joepavitt ,
Thanks for the pointers!
Completely overlooked it in this example node...
